name: Build and Publish image to Docker Hub

on:
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: docker build ./api/ -t ammaralshari/devops-qr-code-api:latest
      - name: push images to docker Hub
        run: |
          docker login -u ammaralshari -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push ammaralshari/devops-qr-code-api:latest